// src/lib/careers/fields/ai-data.ts
import type { CareerFieldModule } from '../types';

export const FIELD_KEY = 'ai-data';

export const BANK: CareerFieldModule['BANK'] = {
  /* ─────────────────────────────────────────────────────────────
   * 1) 데이터 사이언티스트 (초5 · 중5 · 고5 = 15문항)
   * ───────────────────────────────────────────────────────────── */
  'data-scientist': {
    title: '데이터 사이언티스트',
    desc: '문제 정의·데이터 분석·모델링 수행',
    items: [
      // ── 초등(5)
      {
        id: 'ds-el-1',
        grade: '초',
        stem: '데이터 분석의 첫 단계로 가장 알맞은 것은?',
        choices: [
          { key: 'A', label: '문제를 이해하고 목표를 정한다', footnote: 'Problem Definition' },
          { key: 'B', label: '결과를 먼저 정해놓는다' },
          { key: 'C', label: '아무 데이터나 모은다' },
          { key: 'D', label: '색깔만 예쁘게 만든다' },
        ],
        answerKey: 'A',
        hint: '질문이 정확해야 답도 정확해집니다.',
        explanation: '문제 정의가 올바르지 않으면 데이터와 방법 선택이 모두 틀어집니다.',
      },
      {
        id: 'ds-el-2',
        grade: '초',
        stem: '표와 그래프를 사용하는 주된 이유는?',
        choices: [
          { key: 'A', label: '복잡한 정보를 한눈에 이해하기 위해', footnote: 'Data Visualization' },
          { key: 'B', label: '데이터를 숨기기 위해' },
          { key: 'C', label: '용량을 줄이기 위해' },
          { key: 'D', label: '색칠 공부를 하기 위해' },
        ],
        answerKey: 'A',
        hint: '보기 쉽게 만들면 설명도 쉬워집니다.',
        explanation: '시각화는 전달력과 이해도를 높이는 핵심 도구입니다.',
      },
      {
        id: 'ds-el-3',
        grade: '초',
        stem: '다음 중 “데이터”가 될 수 있는 것은?',
        choices: [
          { key: 'A', label: '학교 급식 만족도 설문 결과' },
          { key: 'B', label: '구름 모양 그 자체' },
          { key: 'C', label: '사탕 맛의 느낌' },
          { key: 'D', label: '꿈의 내용 그대로' },
        ],
        answerKey: 'A',
        hint: '기록·저장이 가능한 정보여야 합니다.',
        explanation: '수치·텍스트 등 저장/분석 가능한 형태여야 데이터입니다.',
      },
      {
        id: 'ds-el-4',
        grade: '초',
        stem: '평균(average)은 무엇을 나타내나요?',
        choices: [
          { key: 'A', label: '전체를 대표하는 값', footnote: '합계 ÷ 개수' },
          { key: 'B', label: '가장 큰 값' },
          { key: 'C', label: '가장 작은 값' },
          { key: 'D', label: '임의의 값' },
        ],
        answerKey: 'A',
        hint: '모든 값을 더해 개수로 나눕니다.',
        explanation: '평균은 중심 경향을 보여 주는 대표값입니다.',
      },
      {
        id: 'ds-el-5',
        grade: '초',
        stem: '데이터를 수집할 때 중요한 태도는?',
        choices: [
          { key: 'A', label: '정확하고 정직하게 기록한다', footnote: 'Data Ethics' },
          { key: 'B', label: '정답만 골라 적는다' },
          { key: 'C', label: '맘대로 값을 바꾼다' },
          { key: 'D', label: '틀린 값은 숨긴다' },
        ],
        answerKey: 'A',
        hint: '신뢰가 곧 품질입니다.',
        explanation: '윤리와 정확성이 데이터 과학의 기반입니다.',
      },

      // ── 중등(5)
      {
        id: 'ds-mid-1',
        grade: '중',
        stem: '결측치(missing value)를 다루는 방법으로 적절하지 않은 것은?',
        choices: [
          { key: 'B', label: '모두 0으로 바꾼다' },
          { key: 'A', label: '평균/중앙값으로 대체한다', footnote: 'Imputation' },
          { key: 'C', label: '결측이 많은 열/행은 제거한다' },
          { key: 'D', label: '모델이 허용하면 결측을 별도 값으로 둔다' },
        ],
        answerKey: 'A',
        hint: '무분별한 0 대체는 편향을 유발합니다.',
        explanation: '데이터 특성에 맞는 적절한 대체/제거 전략이 필요합니다.',
      },
      {
        id: 'ds-mid-2',
        grade: '중',
        stem: '데이터 스케일링이 필요한 주된 이유는?',
        choices: [
          { key: 'A', label: '특성 간 단위 차이를 줄여 학습 안정성 향상', footnote: 'Standardization/MinMax' },
          { key: 'B', label: '정답을 바꾸기 위해' },
          { key: 'C', label: '데이터 개수를 늘리기 위해' },
          { key: 'D', label: '색을 예쁘게 하기 위해' },
        ],
        answerKey: 'A',
        hint: '거리 기반 모델일수록 중요합니다.',
        explanation: '스케일 차이는 손실과 경사에 영향을 주므로 정규화가 필요합니다.',
      },
      {
        id: 'ds-mid-3',
        grade: '중',
        stem: '훈련/검증/테스트 데이터로 나누는 목적은?',
        choices: [
          { key: 'A', label: '일반화 성능을 공정하게 평가하기 위해', footnote: 'Generalization' },
          { key: 'B', label: '훈련 속도를 늦추기 위해' },
          { key: 'C', label: '메모리를 낭비하기 위해' },
          { key: 'D', label: '정답을 숨기기 위해' },
        ],
        answerKey: 'A',
        hint: '과적합을 피하고 성능을 객관 평가합니다.',
        explanation: '분리 평가가 모델 과적합 여부를 검증하는 표준입니다.',
      },
      {
        id: 'ds-mid-4',
        grade: '중',
        stem: '시각화에서 상자그림(Box plot)이 유용한 이유는?',
        choices: [
          { key: 'A', label: '분포의 중심과 이상치를 한눈에 보여준다', footnote: 'IQR, median, whisker' },
          { key: 'B', label: '색상 팔레트를 꾸며준다' },
          { key: 'C', label: '샘플 수만 표시한다' },
          { key: 'D', label: '평균만 보여준다' },
        ],
        answerKey: 'A',
        hint: '중앙값과 IQR을 확인할 수 있습니다.',
        explanation: '상자그림은 분포 형태와 이상치를 직관적으로 드러냅니다.',
      },
      {
        id: 'ds-mid-5',
        grade: '중',
        stem: '모델의 정확도(accuracy)가 85%라는 의미는?',
        choices: [
          { key: 'A', label: '전체 예측 중 85%가 맞았다', footnote: 'Correct / All' },
          { key: 'B', label: '양성만 85% 맞췄다' },
          { key: 'C', label: '음성만 85% 맞췄다' },
          { key: 'D', label: '데이터가 85개 있다' },
        ],
        answerKey: 'A',
        hint: '정확도는 전체 기준입니다.',
        explanation: 'Precision/Recall과 구분하여 해석해야 합니다.',
      },

      // ── 고등(5)
      {
        id: 'ds-hi-1',
        grade: '고',
        stem: '과적합(overfitting)을 줄이는 대표적 방법이 아닌 것은?',
        choices: [
          { key: 'B', label: '훈련 에폭을 과도하게 늘린다' },
          { key: 'A', label: '규제(Regularization)를 사용한다', footnote: 'L1/L2, Dropout' },
          { key: 'C', label: '교차검증을 적용한다' },
          { key: 'D', label: '데이터 증강/수집을 한다' },
        ],
        answerKey: 'A',
        hint: '과도한 학습은 오히려 외우게 만듭니다.',
        explanation: '규제, 교차검증, 데이터 증강이 일반적 해결책입니다.',
      },
      {
        id: 'ds-hi-2',
        grade: '고',
        stem: '불균형 데이터에서 Accuracy 대신 고려해야 할 지표는?',
        choices: [
          { key: 'A', label: '정밀도·재현율·F1', footnote: 'Precision/Recall/F1' },
          { key: 'B', label: '파일 크기' },
          { key: 'C', label: '훈련 시간' },
          { key: 'D', label: 'CPU 코어 수' },
        ],
        answerKey: 'A',
        hint: '양성과 음성을 균형 있게 평가해야 합니다.',
        explanation: '불균형일수록 F1/ROC-AUC 같은 지표가 필요합니다.',
      },
      {
        id: 'ds-hi-3',
        grade: '고',
        stem: '특성 중요도(Feature Importance)가 높은 변수의 의미는?',
        choices: [
          { key: 'A', label: '예측에 기여도가 큰 변수', footnote: 'Contribution to prediction' },
          { key: 'B', label: '항상 정답인 변수' },
          { key: 'C', label: '결측이 없는 변수' },
          { key: 'D', label: '스케일이 큰 변수' },
        ],
        answerKey: 'A',
        hint: '모델이 의사결정에 많이 참고한 변수입니다.',
        explanation: '해석가능성을 높이고 피쳐 선택에 도움을 줍니다.',
      },
      {
        id: 'ds-hi-4',
        grade: '고',
        stem: '교차검증(k-fold)의 주된 목적은?',
        choices: [
          { key: 'A', label: '데이터 분할을 바꿔가며 일반화 성능을 안정적으로 추정', footnote: 'Variance 감소' },
          { key: 'B', label: '정답을 바꾼다' },
          { key: 'C', label: '학습 속도만 높인다' },
          { key: 'D', label: '모델 복잡도를 무한정 늘린다' },
        ],
        answerKey: 'A',
        hint: '여러 번 검증하여 편차를 줄입니다.',
        explanation: '훈련/검증 분할을 반복하며 평균 성능을 봅니다.',
      },
      {
        id: 'ds-hi-5',
        grade: '고',
        stem: '데이터 윤리 측면에서 바람직하지 않은 행위는?',
        choices: [
          { key: 'B', label: '결과를 유리하게 보이도록 일부 데이터를 임의로 제거' },
          { key: 'A', label: '개인정보를 비식별 처리한다', footnote: 'Anonymization' },
          { key: 'C', label: '동의 범위 내에서 데이터를 사용한다' },
          { key: 'D', label: '데이터 품질과 출처를 명시한다' },
        ],
        answerKey: 'A',
        hint: '조작·왜곡은 신뢰를 무너뜨립니다.',
        explanation: '연구윤리를 지키는 것이 사회적 신뢰의 기본입니다.',
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────────
   * 2) 인공지능 연구원 (초5 · 중5 · 고5 = 15문항)
   * ───────────────────────────────────────────────────────────── */
  'ai-researcher': {
    title: '인공지능 연구원',
    desc: 'AI 알고리즘 연구·개발',
    items: [
      // ── 초등(5)
      {
        id: 'ar-el-1',
        grade: '초',
        stem: '컴퓨터가 스스로 규칙을 배우게 하는 기술을 무엇이라 하나요?',
        choices: [
          { key: 'A', label: '머신러닝', footnote: 'Machine Learning' },
          { key: 'B', label: '그림그리기' },
          { key: 'C', label: '인터넷 서핑' },
          { key: 'D', label: '타자치기' },
        ],
        answerKey: 'A',
        hint: '데이터에서 패턴을 배웁니다.',
        explanation: '머신러닝은 데이터 기반으로 규칙을 학습하는 기술입니다.',
      },
      {
        id: 'ar-el-2',
        grade: '초',
        stem: '이미지를 보고 고양이/개를 구분하는 일을 무엇이라 하나요?',
        choices: [
          { key: 'A', label: '분류(Classification)', footnote: '라벨 예측' },
          { key: 'B', label: '번역' },
          { key: 'C', label: '소리내기' },
          { key: 'D', label: '그림 색칠' },
        ],
        answerKey: 'A',
        hint: '여러 클래스 중 하나를 고릅니다.',
        explanation: '분류는 지도학습의 대표 과제입니다.',
      },
      {
        id: 'ar-el-3',
        grade: '초',
        stem: '자율주행 자동차가 신호등을 인식하려면 필요한 데이터는?',
        choices: [
          { key: 'A', label: '신호등 이미지와 정답 라벨', footnote: '학습용 GT(Label)' },
          { key: 'B', label: '자동차 색상표' },
          { key: 'C', label: '운전자의 취향' },
          { key: 'D', label: '도로 이름의 유래' },
        ],
        answerKey: 'A',
        hint: '정답이 붙은 데이터가 필요합니다.',
        explanation: '지도학습 기반 인식 모델을 훈련합니다.',
      },
      {
        id: 'ar-el-4',
        grade: '초',
        stem: '챗봇이 사람처럼 대화하려면 무엇이 중요할까요?',
        choices: [
          { key: 'A', label: '많은 대화 데이터와 적절한 학습', footnote: '대규모 말뭉치' },
          { key: 'B', label: '목소리 크기' },
          { key: 'C', label: '키보드 색상' },
          { key: 'D', label: '책상 크기' },
        ],
        answerKey: 'A',
        hint: '언어 데이터를 많이 봐야 합니다.',
        explanation: '자연어 이해/생성은 대용량 데이터가 성능을 좌우합니다.',
      },
      {
        id: 'ar-el-5',
        grade: '초',
        stem: 'AI가 잘못 배운 경우를 고치려면?',
        choices: [
          { key: 'A', label: '데이터를 점검하고 다시 학습한다', footnote: 'Data/Label QA' },
          { key: 'B', label: '컴퓨터를 흔든다' },
          { key: 'C', label: '마우스를 바꾼다' },
          { key: 'D', label: '키캡을 바꾼다' },
        ],
        answerKey: 'A',
        hint: 'Garbage in, garbage out.',
        explanation: '데이터 품질과 라벨 오류가 성능 저하의 큰 원인입니다.',
      },

      // ── 중등(5)
      {
        id: 'ar-mid-1',
        grade: '중',
        stem: '비지도 학습의 대표 과제로 옳은 것은?',
        choices: [
          { key: 'A', label: '군집화(Clustering)', footnote: 'K-means 등' },
          { key: 'B', label: '지도 분류' },
          { key: 'C', label: '회귀' },
          { key: 'D', label: '강화학습 정책 학습' },
        ],
        answerKey: 'A',
        hint: '정답 라벨 없이 구조를 찾습니다.',
        explanation: '비지도는 데이터의 숨은 구조를 파악합니다.',
      },
      {
        id: 'ar-mid-2',
        grade: '중',
        stem: '과소적합(underfitting)의 특징은?',
        choices: [
          { key: 'A', label: '훈련/검증 모두 성능이 낮다', footnote: '모델이 너무 단순' },
          { key: 'B', label: '훈련만 높고 검증은 낮다' },
          { key: 'C', label: '검증만 높다' },
          { key: 'D', label: '둘 다 매우 높다' },
        ],
        answerKey: 'A',
        hint: '모델 용량이 부족하거나 학습이 덜 됐을 때',
        explanation: '복잡도를 높이거나 더 학습해야 합니다.',
      },
      {
        id: 'ar-mid-3',
        grade: '중',
        stem: 'CNN(합성곱 신경망)이 주로 다루는 데이터는?',
        choices: [
          { key: 'A', label: '이미지/영상', footnote: 'Spatial feature' },
          { key: 'B', label: '표형 데이터' },
          { key: 'C', label: '순차 텍스트' },
          { key: 'D', label: '오디오 파형' },
        ],
        answerKey: 'A',
        hint: '공간적 패턴을 잘 포착합니다.',
        explanation: '합성곱은 지역적인 특징을 추출합니다.',
      },
      {
        id: 'ar-mid-4',
        grade: '중',
        stem: 'RNN/LSTM이 강점을 보이는 영역은?',
        choices: [
          { key: 'A', label: '시계열·자연어 등 순차 데이터', footnote: 'Sequence modeling' },
          { key: 'B', label: '2D 영상만' },
          { key: 'C', label: '정적 이미지 분류만' },
          { key: 'D', label: '좌표 변환' },
        ],
        answerKey: 'A',
        hint: '앞뒤 문맥이 중요합니다.',
        explanation: '순서를 고려해 정보를 누적·저장합니다.',
      },
      {
        id: 'ar-mid-5',
        grade: '중',
        stem: '전이학습(Transfer Learning)의 장점은?',
        choices: [
          { key: 'A', label: '적은 데이터로도 높은 성능을 낼 수 있다', footnote: 'Pretrained weights' },
          { key: 'B', label: '새 모델을 매번 처음부터 학습해야 한다' },
          { key: 'C', label: '학습 시간이 반드시 늘어난다' },
          { key: 'D', label: '응용이 불가능하다' },
        ],
        answerKey: 'A',
        hint: '사전학습 지식을 재사용합니다.',
        explanation: '범용 표현을 활용해 데이터/시간을 절약합니다.',
      },

      // ── 고등(5)
      {
        id: 'ar-hi-1',
        grade: '고',
        stem: '하이퍼파라미터 튜닝의 일반적 방법이 아닌 것은?',
        choices: [
          { key: 'B', label: '임의 추정 후 고정' },
          { key: 'A', label: '그리드/랜덤 서치', footnote: 'Grid/Random Search' },
          { key: 'C', label: '베이지안 최적화' },
          { key: 'D', label: '교차검증과 병행' },
        ],
        answerKey: 'A',
        hint: '체계적 탐색이 필요합니다.',
        explanation: '무작정 고정은 최적 설정을 놓칠 가능성이 큽니다.',
      },
      {
        id: 'ar-hi-2',
        grade: '고',
        stem: '학습률(learning rate)이 너무 크면 발생하기 쉬운 문제는?',
        choices: [
          { key: 'A', label: '발산하여 수렴하지 않음', footnote: 'Divergence' },
          { key: 'B', label: '매우 느리게 수렴' },
          { key: 'C', label: '항상 최적점에 도달' },
          { key: 'D', label: '정확도와 무관' },
        ],
        answerKey: 'A',
        hint: '손실이 요동치며 커집니다.',
        explanation: '적절한 스케줄링/워밍업이 필요합니다.',
      },
      {
        id: 'ar-hi-3',
        grade: '고',
        stem: '정규화(Regularization)의 역할로 옳은 것은?',
        choices: [
          { key: 'A', label: '모델 복잡도를 억제하여 과적합을 완화', footnote: 'L1/L2, Dropout' },
          { key: 'B', label: '데이터 개수를 늘린다' },
          { key: 'C', label: '정답 라벨을 바꾼다' },
          { key: 'D', label: '훈련을 중단한다' },
        ],
        answerKey: 'A',
        hint: '복잡도를 제어해 일반화 능력을 높입니다.',
        explanation: '가중치 패널티/무작위 차단 등으로 과적합을 줄입니다.',
      },
      {
        id: 'ar-hi-4',
        grade: '고',
        stem: 'ROC-AUC가 높은 모델의 해석으로 적절한 것은?',
        choices: [
          { key: 'A', label: '임계값에 덜 민감하게 분류능력이 우수', footnote: 'Threshold-independent' },
          { key: 'B', label: '정확도만 높음' },
          { key: 'C', label: '재현율만 높음' },
          { key: 'D', label: '적중률만 높음' },
        ],
        answerKey: 'A',
        hint: '다양한 임계값에서 성능을 통합 측정합니다.',
        explanation: '클래스 불균형 상황에서 비교에 유용합니다.',
      },
      {
        id: 'ar-hi-5',
        grade: '고',
        stem: 'AI 연구에서 재현성(reproducibility)을 높이기 위한 실무 방식은?',
        choices: [
          { key: 'A', label: '실험 로그·코드·데이터 버전을 함께 기록', footnote: 'Seed·Config·Artifact 관리' },
          { key: 'B', label: '결과 이미지만 남긴다' },
          { key: 'C', label: '코드는 비공유, 구두 보고만' },
          { key: 'D', label: '데이터 출처를 생략' },
        ],
        answerKey: 'A',
        hint: '동일 설정으로 다시 실행 가능해야 합니다.',
        explanation: 'MLops/실험관리 도구를 사용해 추적성을 확보합니다.',
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────────
   * 3) 빅데이터 분석가 (초5 · 중5 · 고5 = 15문항)
   * ───────────────────────────────────────────────────────────── */
  'bigdata-analyst': {
    title: '빅데이터 분석가',
    desc: '데이터 수집·가공·시각화·예측',
    items: [
      // ── 초등(5)
      {
        id: 'ba-el-1',
        grade: '초',
        stem: '많은 양의 데이터를 빠르게 모아 저장하는 시스템은?',
        choices: [
          { key: 'A', label: '데이터 웨어하우스/레이크', footnote: 'DW / Data Lake' },
          { key: 'B', label: '앨범' },
          { key: 'C', label: '연필통' },
          { key: 'D', label: '지우개' },
        ],
        answerKey: 'A',
        hint: '분석/보관을 위한 저장소입니다.',
        explanation: '대용량 데이터를 효율적으로 저장·조회합니다.',
      },
      {
        id: 'ba-el-2',
        grade: '초',
        stem: '센서에서 계속 들어오는 데이터를 무엇이라 할까요?',
        choices: [
          { key: 'A', label: '스트리밍 데이터', footnote: 'Streaming' },
          { key: 'B', label: '정적 데이터' },
          { key: 'C', label: '이미지 파일만' },
          { key: 'D', label: '한글 문서만' },
        ],
        answerKey: 'A',
        hint: '끊임없이 흐르는 데이터',
        explanation: '실시간 분석/알림에 활용됩니다.',
      },
      {
        id: 'ba-el-3',
        grade: '초',
        stem: '지도에서 배달 지점을 찍어 보여주는 것은 어떤 시각화일까요?',
        choices: [
          { key: 'A', label: '지도 시각화', footnote: 'Geo Visualization' },
          { key: 'B', label: '악보' },
          { key: 'C', label: '퍼즐' },
          { key: 'D', label: '만화' },
        ],
        answerKey: 'A',
        hint: '위치 정보가 핵심입니다.',
        explanation: '경도·위도 데이터를 시각화합니다.',
      },
      {
        id: 'ba-el-4',
        grade: '초',
        stem: '판매량이 가장 많은 시간을 찾으려면 어떤 차트가 좋을까요?',
        choices: [
          { key: 'A', label: '막대/선 차트', footnote: 'Bar/Line' },
          { key: 'B', label: '도넛 간식' },
          { key: 'C', label: '스티커북' },
          { key: 'D', label: '색종이' },
        ],
        answerKey: 'A',
        hint: '시간에 따른 변화를 봅니다.',
        explanation: '선형·막대는 시계열 트렌드를 파악하는 기본입니다.',
      },
      {
        id: 'ba-el-5',
        grade: '초',
        stem: '한 달 용돈 지출을 한눈에 보려면 가장 먼저 할 일은?',
        choices: [
          { key: 'A', label: '항목별로 기록하여 표로 정리', footnote: '수입/지출 표' },
          { key: 'B', label: '기억에만 의존' },
          { key: 'C', label: '대충 추측' },
          { key: 'D', label: '모두 삭제' },
        ],
        answerKey: 'A',
        hint: '기록이 분석의 시작입니다.',
        explanation: '구체적 기록이 있어야 패턴을 찾을 수 있습니다.',
      },

      // ── 중등(5)
      {
        id: 'ba-mid-1',
        grade: '중',
        stem: 'ETL 프로세스에서 T(Transform)의 예로 적절한 것은?',
        choices: [
          { key: 'A', label: '형식 통일·결측 보정·집계', footnote: '정제/가공 단계' },
          { key: 'B', label: '외부 API에서 원천 추출' },
          { key: 'C', label: '결과 리포트 작성' },
          { key: 'D', label: '대시보드 배포' },
        ],
        answerKey: 'A',
        hint: '추출-변환-적재 중 변환 단계입니다.',
        explanation: '분석 가능한 형태로 표준화/가공합니다.',
      },
      {
        id: 'ba-mid-2',
        grade: '중',
        stem: '로그 데이터의 이상 행동을 찾는 데 유용한 방법은?',
        choices: [
          { key: 'A', label: '이상치 탐지(Anomaly Detection)', footnote: 'IsolationForest 등' },
          { key: 'B', label: '무작위 추출' },
          { key: 'C', label: '색상 변경' },
          { key: 'D', label: '파일 이름 바꾸기' },
        ],
        answerKey: 'A',
        hint: '정상 패턴에서 벗어난 점을 찾습니다.',
        explanation: '보안/품질 모니터링에서 중요합니다.',
      },
      {
        id: 'ba-mid-3',
        grade: '중',
        stem: '관계형 데이터베이스에서 “조인(Join)”의 목적은?',
        choices: [
          { key: 'A', label: '여러 테이블의 관련 정보를 합친다', footnote: 'Foreign Key' },
          { key: 'B', label: '테이블을 삭제' },
          { key: 'C', label: '인덱스를 제거' },
          { key: 'D', label: '권한을 초기화' },
        ],
        answerKey: 'A',
        hint: '공통 키를 기준으로 합칩니다.',
        explanation: '정규화된 데이터를 분석용으로 결합합니다.',
      },
      {
        id: 'ba-mid-4',
        grade: '중',
        stem: '파레토 차트(80/20 법칙) 분석의 목표는?',
        choices: [
          { key: 'A', label: '주요 원인 소수를 찾아 집중 개선', footnote: 'Pareto principle' },
          { key: 'B', label: '모든 항목을 동일하게 취급' },
          { key: 'C', label: '임의의 항목만 본다' },
          { key: 'D', label: '평균만 본다' },
        ],
        answerKey: 'A',
        hint: '중요한 소수에 집중합니다.',
        explanation: '불량/클레임 등 핵심 원인 파악에 효과적입니다.',
      },
      {
        id: 'ba-mid-5',
        grade: '중',
        stem: '대시보드 설계 시 가장 중요한 원칙은?',
        choices: [
          { key: 'A', label: '의사결정에 필요한 핵심 지표를 명확히 보여준다', footnote: 'Actionable Metrics' },
          { key: 'B', label: '그래픽을 최대한 화려하게' },
          { key: 'C', label: '표시할 수 있는 건 모두 표시' },
          { key: 'D', label: '텍스트만 가득' },
        ],
        answerKey: 'A',
        hint: '보고서가 아니라 “운영 도구”입니다.',
        explanation: '한 눈에 상태/변화를 파악하고 행동으로 이어져야 합니다.',
      },

      // ── 고등(5)
      {
        id: 'ba-hi-1',
        grade: '고',
        stem: '피처 엔지니어링에서 “원-핫 인코딩”의 목적은?',
        choices: [
          { key: 'A', label: '범주형 변수를 모델이 다룰 수 있게 숫자로 변환', footnote: 'One-Hot' },
          { key: 'B', label: '결측을 생성' },
          { key: 'C', label: '데이터를 압축' },
          { key: 'D', label: '정답을 바꿈' },
        ],
        answerKey: 'A',
        hint: '범주 → 벡터(0/1)',
        explanation: '순서가 없는 범주를 안전하게 표현합니다.',
      },
      {
        id: 'ba-hi-2',
        grade: '고',
        stem: '시계열 예측에서 “자기상관(ACF)”이 높은 의미는?',
        choices: [
          { key: 'A', label: '과거 값이 현재 값에 강하게 영향', footnote: 'Autocorrelation' },
          { key: 'B', label: '무작위 잡음' },
          { key: 'C', label: '항상 추세 없음' },
          { key: 'D', label: '데이터 수가 매우 적음' },
        ],
        answerKey: 'A',
        hint: '패턴의 반복·지속을 시사합니다.',
        explanation: '모형 선택(ARIMA 등)에 참고됩니다.',
      },
      {
        id: 'ba-hi-3',
        grade: '고',
        stem: '샘플 불균형을 다루는 기법으로 부적절한 것은?',
        choices: [
          { key: 'C', label: '소수 클래스 더 다운샘플링만 무조건 수행' },
          { key: 'B', label: '가중치 조정' },
          { key: 'A', label: 'SMOTE 등 오버샘플링', footnote: 'Synthetic Minority' },
          { key: 'D', label: '지표를 F1/ROC-AUC로 확인' },
        ],
        answerKey: 'A',
        hint: '정보 손실이 심할 수 있습니다.',
        explanation: '여러 기법을 균형 있게 사용해야 합니다.',
      },
      {
        id: 'ba-hi-4',
        grade: '고',
        stem: 'AB 테스트에서 “유의수준(α)”은 무엇을 의미하나요?',
        choices: [
          { key: 'A', label: '귀무가설이 참인데도 기각할 확률', footnote: 'Type I error' },
          { key: 'B', label: '대립가설이 참일 확률' },
          { key: 'C', label: '표본평균의 값' },
          { key: 'D', label: '효과 크기의 절대값' },
        ],
        answerKey: 'A',
        hint: '거짓 양성의 허용률입니다.',
        explanation: '일반적으로 0.05 등으로 설정합니다.',
      },
      {
        id: 'ba-hi-5',
        grade: '고',
        stem: '파이프라인화(Feature→Model→Eval)의 장점으로 옳은 것은?',
        choices: [
          { key: 'A', label: '재현성·자동화·운영 이전(MLOps)에 유리', footnote: 'Reproducible pipeline' },
          { key: 'B', label: '수작업이 늘어난다' },
          { key: 'C', label: '실험 추적이 어려워진다' },
          { key: 'D', label: '배포가 불가능해진다' },
        ],
        answerKey: 'A',
        hint: '일관된 절차가 품질을 올립니다.',
        explanation: '스케줄링/배포/모니터링과의 연계가 쉬워집니다.',
      },
    ],
  },
};
