// src/lib/careers/fields/software-app.ts
import { CareerFieldModule } from '../types';

export const FIELD_KEY = 'software-app';

export const BANK: CareerFieldModule['BANK'] = {
  /* ─────────────────────────────────────────────────────────────
   * 1) 프론트엔드 개발자 (초5 · 중5 · 고5 = 15문항)
   * ───────────────────────────────────────────────────────────── */
  'frontend-dev': {
    title: '프론트엔드 개발자',
    desc: '웹 UI/UX 구현, 상태관리, 접근성·성능 최적화',
    items: [
      // ── 초등(5)
      {
        id: 'fe-el-1',
        grade: '초',
        stem: '웹페이지의 구조를 표현하는 언어는?',
        choices: [
          { key: 'A', label: 'HTML', footnote: 'HyperText Markup Language' },
          { key: 'B', label: 'JPEG' },
          { key: 'C', label: 'MP3' },
          { key: 'D', label: 'PDF' },
        ],
        answerKey: 'A',
        hint: '태그로 제목·단락을 만듭니다.',
        explanation: 'HTML은 문서 구조를, CSS는 디자인을, JS는 동작을 담당합니다.',
      },
      {
        id: 'fe-el-2',
        grade: '초',
        stem: '버튼을 눌렀을 때 색이 변하도록 “모양”을 꾸미는 기술은?',
        choices: [
          { key: 'A', label: 'CSS', footnote: 'Cascading Style Sheets' },
          { key: 'B', label: 'DNS' },
          { key: 'C', label: 'URL' },
          { key: 'D', label: 'HTTP' },
        ],
        answerKey: 'A',
        hint: '스타일·레이아웃을 담당합니다.',
        explanation: 'CSS는 색상, 글꼴, 배치 등을 정의합니다.',
      },
      {
        id: 'fe-el-3',
        grade: '초',
        stem: '웹페이지에서 “클릭” 같은 동작을 처리하는 언어는?',
        choices: [
          { key: 'A', label: '자바스크립트', footnote: 'JavaScript' },
          { key: 'B', label: 'CSS' },
          { key: 'C', label: 'SVG' },
          { key: 'D', label: 'PNG' },
        ],
        answerKey: 'A',
        hint: '이벤트를 다룹니다.',
        explanation: '자바스크립트는 동적 상호작용을 구현합니다.',
      },
      {
        id: 'fe-el-4',
        grade: '초',
        stem: '이미지를 불러오지 않고도 제목과 본문을 이해할 수 있게 만드는 원칙은?',
        choices: [
          { key: 'A', label: '웹 접근성', footnote: 'Accessibility(ALT, 대비, 키보드)' },
          { key: 'B', label: '과몰입' },
          { key: 'C', label: '랜덤성' },
          { key: 'D', label: '오타 만들기' },
        ],
        answerKey: 'A',
        hint: '모두에게 쓰기 편해야 합니다.',
        explanation: '대체 텍스트·명확한 대비·키보드 내비게이션 등이 포함됩니다.',
      },
      {
        id: 'fe-el-5',
        grade: '초',
        stem: '여러 페이지에서 같은 머리글/바닥글을 반복해서 쓰려면 무엇을 만들까요?',
        choices: [
          { key: 'A', label: '컴포넌트', footnote: '반복 UI 재사용' },
          { key: 'B', label: '스크린샷' },
          { key: 'C', label: '그림 파일' },
          { key: 'D', label: '프린트물' },
        ],
        answerKey: 'A',
        hint: '재사용 단위입니다.',
        explanation: '컴포넌트화는 유지보수성과 일관성을 높입니다.',
      },

      // ── 중등(5)
      {
        id: 'fe-mid-1',
        grade: '중',
        stem: '리액트에서 화면을 쪼개 재사용 가능한 단위를 무엇이라 하나요?',
        choices: [
          { key: 'A', label: '컴포넌트', footnote: 'Component' },
          { key: 'B', label: '쿠키' },
          { key: 'C', label: '세션' },
          { key: 'D', label: '도메인' },
        ],
        answerKey: 'A',
        hint: '함수·JSX로 구성됩니다.',
        explanation: '컴포넌트는 입력(props)과 상태(state)에 따라 UI를 그립니다.',
      },
      {
        id: 'fe-mid-2',
        grade: '중',
        stem: '리스트 렌더링 시 각 항목에 꼭 지정해야 하는 속성은?',
        choices: [
          { key: 'A', label: 'key', footnote: '가상 DOM 비교 최적화' },
          { key: 'B', label: 'src' },
          { key: 'C', label: 'href' },
          { key: 'D', label: 'alt' },
        ],
        answerKey: 'A',
        hint: '고유 식별자를 뜻합니다.',
        explanation: 'key가 없으면 재정렬·추가 시 성능·정확성 문제가 생깁니다.',
      },
      {
        id: 'fe-mid-3',
        grade: '중',
        stem: 'SPA에서 새로고침 없이 주소만 바뀌게 하는 기술은?',
        choices: [
          { key: 'A', label: '클라이언트 라우팅', footnote: 'History API' },
          { key: 'B', label: '바이러스 검사' },
          { key: 'C', label: 'FTP' },
          { key: 'D', label: 'CDN' },
        ],
        answerKey: 'A',
        hint: 'URL만 바뀌고 화면은 부분 교체됩니다.',
        explanation: '클라이언트 라우터가 경로에 맞는 컴포넌트를 보여 줍니다.',
      },
      {
        id: 'fe-mid-4',
        grade: '중',
        stem: '이미지/스크립트를 필요할 때만 불러 성능을 높이는 기법은?',
        choices: [
          { key: 'A', label: '지연 로딩', footnote: 'Lazy Loading' },
          { key: 'B', label: '과도한 폴링' },
          { key: 'C', label: '무한 리로드' },
          { key: 'D', label: '인라인 전부 삽입' },
        ],
        answerKey: 'A',
        hint: '첫 화면 속도를 개선합니다.',
        explanation: '코드 스플리팅·이미지 lazy 속성 등으로 구현합니다.',
      },
      {
        id: 'fe-mid-5',
        grade: '중',
        stem: '색 대비, 폰트 크기, 포커스 표시를 점검하는 이유는?',
        choices: [
          { key: 'A', label: '접근성 기준을 지키기 위해', footnote: 'WCAG' },
          { key: 'B', label: '랜덤 효과를 주기 위해' },
          { key: 'C', label: '코드 줄 수 늘리기' },
          { key: 'D', label: '비밀 모드' },
        ],
        answerKey: 'A',
        hint: '모든 사용자의 이용 가능성 보장',
        explanation: '접근성은 법·윤리·사용성 측면에서 중요합니다.',
      },

      // ── 고등(5)
      {
        id: 'fe-hi-1',
        grade: '고',
        stem: '대량 리스트를 매끄럽게 스크롤하려면 효과적인 기법은?',
        choices: [
          { key: 'A', label: '가상 스크롤', footnote: 'Virtualization' },
          { key: 'B', label: '모든 아이템 한 번에 렌더' },
          { key: 'C', label: 'DOM 강제 리플로우 반복' },
          { key: 'D', label: '이미지 원본 그대로 사용' },
        ],
        answerKey: 'A',
        hint: '화면에 보이는 영역만 그립니다.',
        explanation: '렌더 범위를 제한하여 성능을 확보합니다.',
      },
      {
        id: 'fe-hi-2',
        grade: '고',
        stem: 'XSS를 예방하기 위한 올바른 방법은?',
        choices: [
          { key: 'A', label: '사용자 입력 이스케이프/검증', footnote: 'Escape/Sanitize' },
          { key: 'B', label: '스크립트 태그를 더 추가' },
          { key: 'C', label: '콘솔만 숨기기' },
          { key: 'D', label: '쿠키를 아무 곳에 저장' },
        ],
        answerKey: 'A',
        hint: '입력은 항상 불신하고 처리합니다.',
        explanation: '콘텐츠 보안 정책(CSP)과 함께 적용하면 효과적입니다.',
      },
      {
        id: 'fe-hi-3',
        grade: '고',
        stem: '웹 성능 측정 지표로 LCP·CLS·FID는 각각 무엇을 다루나요?',
        choices: [
          { key: 'A', label: '로딩·레이아웃 안정·상호작용', footnote: 'Core Web Vitals' },
          { key: 'B', label: '보안·암호화·로그' },
          { key: 'C', label: '이미지 색상·포맷·용량만' },
          { key: 'D', label: '광고 클릭률' },
        ],
        answerKey: 'A',
        hint: '사용자 체감 성능과 직결',
        explanation: '구글 CWV는 실제 사용자 경험을 반영합니다.',
      },
      {
        id: 'fe-hi-4',
        grade: '고',
        stem: '상태관리 도구가 필요한 이유로 “가장” 적절한 것은?',
        choices: [
          { key: 'A', label: '컴포넌트 간 상태 공유/예측 가능성 확보', footnote: 'Single source of truth' },
          { key: 'B', label: '파일 개수를 늘리기 위해' },
          { key: 'C', label: '모든 페이지를 서버에서만 렌더' },
          { key: 'D', label: '이미지를 꾸미기 위해' },
        ],
        answerKey: 'A',
        hint: '복잡도가 올라갈수록 중요합니다.',
        explanation: '전역 상태/캐시 일관성이 핵심입니다.',
      },
      {
        id: 'fe-hi-5',
        grade: '고',
        stem: 'CSR과 SSR의 차이에 대한 설명으로 옳은 것은?',
        choices: [
          { key: 'A', label: 'CSR은 브라우저에서, SSR은 서버에서 최초 렌더', footnote: 'Client vs Server Render' },
          { key: 'B', label: '둘 다 서버에서만 렌더' },
          { key: 'C', label: '둘 다 브라우저에서만 렌더' },
          { key: 'D', label: '차이가 없다' },
        ],
        answerKey: 'A',
        hint: '첫 페인트 속도·SEO에 영향',
        explanation: '하이브리드/스트리밍 등 상황에 맞게 선택합니다.',
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────────
   * 2) 백엔드 개발자 (초5 · 중5 · 고5 = 15문항)
   * ───────────────────────────────────────────────────────────── */
  'backend-dev': {
    title: '백엔드 개발자',
    desc: 'API·비즈니스 로직·데이터베이스·보안',
    items: [
      // ── 초등(5)
      {
        id: 'be-el-1',
        grade: '초',
        stem: '사용자의 요청을 받아 처리하고 응답을 보내는 곳은?',
        choices: [
          { key: 'A', label: '서버', footnote: 'Server' },
          { key: 'B', label: '연필' },
          { key: 'C', label: '색종이' },
          { key: 'D', label: '지우개' },
        ],
        answerKey: 'A',
        hint: '백엔드는 서버에서 동작합니다.',
        explanation: '클라이언트 요청을 받아 로직을 수행하고 응답합니다.',
      },
      {
        id: 'be-el-2',
        grade: '초',
        stem: '정보를 오래 보관하는 곳은?',
        choices: [
          { key: 'A', label: '데이터베이스', footnote: 'Database' },
          { key: 'B', label: '그림일기' },
          { key: 'C', label: '모래시계' },
          { key: 'D', label: '고무지우개' },
        ],
        answerKey: 'A',
        hint: '자료 저장소입니다.',
        explanation: 'DB는 데이터를 안전하고 효율적으로 보관합니다.',
      },
      {
        id: 'be-el-3',
        grade: '초',
        stem: '여러 사람이 같은 정보를 동시에 바꾸면 문제가 생길 수 있어요. 이를 막는 기술은?',
        choices: [
          { key: 'A', label: '트랜잭션', footnote: '원자성·일관성' },
          { key: 'B', label: '그림자놀이' },
          { key: 'C', label: '종이접기' },
          { key: 'D', label: '북치기' },
        ],
        answerKey: 'A',
        hint: '하나의 작업 단위로 묶습니다.',
        explanation: '실패 시 롤백하여 정합성을 지킵니다.',
      },
      {
        id: 'be-el-4',
        grade: '초',
        stem: '비밀번호를 그대로 저장하지 않도록 하는 기법은?',
        choices: [
          { key: 'A', label: '해시', footnote: 'Hash' },
          { key: 'B', label: '붙여넣기' },
          { key: 'C', label: '인쇄' },
          { key: 'D', label: '보관함 열어두기' },
        ],
        answerKey: 'A',
        hint: '일방향 함수',
        explanation: '해시와 솔트로 안전하게 관리합니다.',
      },
      {
        id: 'be-el-5',
        grade: '초',
        stem: '여러 정보를 한 줄로 보내는 HTTP 메서드는 주로 무엇일까요?',
        choices: [
          { key: 'A', label: 'POST', footnote: 'Create/Body' },
          { key: 'B', label: 'GET' },
          { key: 'C', label: 'PRINT' },
          { key: 'D', label: 'SLEEP' },
        ],
        answerKey: 'A',
        hint: '본문(body)을 가집니다.',
        explanation: 'POST는 주로 생성/전송에 사용됩니다.',
      },

      // ── 중등(5)
      {
        id: 'be-mid-1',
        grade: '중',
        stem: 'REST API에서 “리소스”를 식별하는 표준 방식은?',
        choices: [
          { key: 'A', label: 'URL 경로', footnote: '/users/123' },
          { key: 'B', label: '쿠키 이름' },
          { key: 'C', label: 'HTML 주석' },
          { key: 'D', label: '색상코드' },
        ],
        answerKey: 'A',
        hint: '명사 형태로 표현합니다.',
        explanation: '행동은 메서드로, 대상은 URL로 표현합니다.',
      },
      {
        id: 'be-mid-2',
        grade: '중',
        stem: 'DB 인덱스의 주요 목적은?',
        choices: [
          { key: 'A', label: '조회 속도 향상', footnote: 'B-Tree/Hash' },
          { key: 'B', label: '보안 암호화' },
          { key: 'C', label: '데이터 삭제' },
          { key: 'D', label: '파일 압축' },
        ],
        answerKey: 'A',
        hint: '책의 목차처럼',
        explanation: '인덱스는 읽기 성능을 높이지만 쓰기 비용이 증가할 수 있습니다.',
      },
      {
        id: 'be-mid-3',
        grade: '중',
        stem: 'JWT 토큰은 주로 어디에 담아 전달하나요?',
        choices: [
          { key: 'A', label: 'HTTP 헤더', footnote: 'Authorization: Bearer' },
          { key: 'B', label: '이미지 픽셀' },
          { key: 'C', label: 'CSS 주석' },
          { key: 'D', label: 'DB 인덱스' },
        ],
        answerKey: 'A',
        hint: '요청 헤더에 첨부',
        explanation: '세션 없이 인증 정보를 전파하는 방식입니다.',
      },
      {
        id: 'be-mid-4',
        grade: '중',
        stem: '캐시를 사용하면 좋은 이유로 가장 적절한 것은?',
        choices: [
          { key: 'A', label: '반복 조회를 빠르게 하고 서버 부하 감소', footnote: 'Caching' },
          { key: 'B', label: '데이터를 영원히 숨김' },
          { key: 'C', label: '보안을 약화' },
          { key: 'D', label: '오류를 늘림' },
        ],
        answerKey: 'A',
        hint: 'TTL/무효화 전략 필요',
        explanation: '읽기 많은 시스템에서 필수적입니다.',
      },
      {
        id: 'be-mid-5',
        grade: '중',
        stem: '파일 업로드와 같은 장기 작업은 어떤 처리 방식이 적절한가요?',
        choices: [
          { key: 'A', label: '비동기 처리/큐', footnote: 'Async/Queue' },
          { key: 'B', label: '동기 블로킹' },
          { key: 'C', label: '무한 대기' },
          { key: 'D', label: '페이지 강제 새로고침' },
        ],
        answerKey: 'A',
        hint: '응답 지연을 최소화',
        explanation: '워커/큐로 백그라운드 처리하고 진행상태를 통지합니다.',
      },

      // ── 고등(5)
      {
        id: 'be-hi-1',
        grade: '고',
        stem: '관계형 DB 트랜잭션 격리수준에서 팬텀 리드를 방지하는 수준은?',
        choices: [
          { key: 'A', label: 'Repeatable Read/Serializable', footnote: 'DBMS마다 차이' },
          { key: 'B', label: 'Read Uncommitted' },
          { key: 'C', label: 'Read Committed' },
          { key: 'D', label: 'No Isolation' },
        ],
        answerKey: 'A',
        hint: '동시성 문제를 단계적으로 완화',
        explanation: '가장 엄격한 Serializable은 성능 비용이 큽니다.',
      },
      {
        id: 'be-hi-2',
        grade: '고',
        stem: '수평 확장을 위해 여러 서버로 요청을 분산하는 구성은?',
        choices: [
          { key: 'A', label: '로드 밸런싱', footnote: 'Load Balancing' },
          { key: 'B', label: '하드코딩' },
          { key: 'C', label: '단일 서버 고정' },
          { key: 'D', label: 'LAN 케이블 제거' },
        ],
        answerKey: 'A',
        hint: '가용성과 확장성',
        explanation: '라운드로빈/가중치/헬스체크 등을 함께 사용합니다.',
      },
      {
        id: 'be-hi-3',
        grade: '고',
        stem: 'CQRS를 도입하는 주된 이점은?',
        choices: [
          { key: 'A', label: '읽기/쓰기 분리로 확장성과 성능 향상', footnote: 'Command/Query' },
          { key: 'B', label: '보안 무력화' },
          { key: 'C', label: '버그 유도' },
          { key: 'D', label: '코드 삭제' },
        ],
        answerKey: 'A',
        hint: '읽기 집약 시스템에 효과적',
        explanation: '쓰기 모델과 읽기 모델을 분리해 최적화합니다.',
      },
      {
        id: 'be-hi-4',
        grade: '고',
        stem: '메시지 브로커를 사용하는 가장 타당한 이유는?',
        choices: [
          { key: 'A', label: '서비스 간 결합도를 낮추고 비동기 처리', footnote: 'Kafka/RabbitMQ' },
          { key: 'B', label: '트랜잭션 제거' },
          { key: 'C', label: '로그를 지우기' },
          { key: 'D', label: '서버를 1대로 줄이기' },
        ],
        answerKey: 'A',
        hint: '확장성과 복원력 향상',
        explanation: '이벤트 기반 아키텍처에서 핵심 컴포넌트입니다.',
      },
      {
        id: 'be-hi-5',
        grade: '고',
        stem: 'OAuth 2.0에서 리소스 접근을 위임받는 주체는?',
        choices: [
          { key: 'A', label: '클라이언트 애플리케이션', footnote: 'Access Token' },
          { key: 'B', label: '네트워크 케이블' },
          { key: 'C', label: '데이터센터 건물' },
          { key: 'D', label: '디스플레이' },
        ],
        answerKey: 'A',
        hint: '사용자 대신 권한 위임',
        explanation: '인가 코드 플로우 등 시나리오를 따릅니다.',
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────────
   * 3) 모바일 앱 개발자 (초5 · 중5 · 고5 = 15문항)
   * ───────────────────────────────────────────────────────────── */
  'mobile-dev': {
    title: '모바일 앱 개발자',
    desc: 'iOS/Android 네이티브·크로스 플랫폼, 성능·배포',
    items: [
      // ── 초등(5)
      {
        id: 'mo-el-1',
        grade: '초',
        stem: '스마트폰에서 실행되는 작은 프로그램을 무엇이라 하나요?',
        choices: [
          { key: 'A', label: '앱', footnote: 'Application' },
          { key: 'B', label: '사진' },
          { key: 'C', label: '노래' },
          { key: 'D', label: '벽지' },
        ],
        answerKey: 'A',
        hint: '설치하고 실행합니다.',
        explanation: '앱은 특정 기능을 제공하는 소프트웨어입니다.',
      },
      {
        id: 'mo-el-2',
        grade: '초',
        stem: '화면을 넘길 때 부드럽게 보이게 하는 요소는?',
        choices: [
          { key: 'A', label: '애니메이션', footnote: 'Transition' },
          { key: 'B', label: '정전' },
          { key: 'C', label: '종이' },
          { key: 'D', label: '비누' },
        ],
        answerKey: 'A',
        hint: '전환 효과',
        explanation: '사용자 경험을 좋게 합니다.',
      },
      {
        id: 'mo-el-3',
        grade: '초',
        stem: '앱에서 “설정”을 바꾸면 다시 켜도 유지되게 저장하는 곳은?',
        choices: [
          { key: 'A', label: '로컬 저장소', footnote: 'Preferences/Storage' },
          { key: 'B', label: '종이 공책' },
          { key: 'C', label: '메모지' },
          { key: 'D', label: '스티커' },
        ],
        answerKey: 'A',
        hint: '영속 저장',
        explanation: '키-값 저장소나 DB를 사용합니다.',
      },
      {
        id: 'mo-el-4',
        grade: '초',
        stem: '앱 아이콘을 누르면 처음 보이는 화면을 무엇이라 하나요?',
        choices: [
          { key: 'A', label: '런치/시작 화면', footnote: 'Launch/Splash' },
          { key: 'B', label: '휴지통' },
          { key: 'C', label: '광고 전단지' },
          { key: 'D', label: '사진첩' },
        ],
        answerKey: 'A',
        hint: '앱을 소개하는 첫 인상',
        explanation: '앱 로딩 동안 보이는 화면입니다.',
      },
      {
        id: 'mo-el-5',
        grade: '초',
        stem: '앱에서 “뒤로가기” 버튼의 역할은?',
        choices: [
          { key: 'A', label: '이전 화면으로 돌아간다' },
          { key: 'B', label: '앱을 삭제한다' },
          { key: 'C', label: '사진을 찍는다' },
          { key: 'D', label: '충전을 시작한다' },
        ],
        answerKey: 'A',
        hint: '이동 내비게이션',
        explanation: '스택에서 이전 화면으로 이동합니다.',
      },

      // ── 중등(5)
      {
        id: 'mo-mid-1',
        grade: '중',
        stem: '네이티브 앱과 크로스 플랫폼 앱의 차이로 옳은 것은?',
        choices: [
          { key: 'A', label: '네이티브는 플랫폼 전용, 크로스는 공용 코드', footnote: 'Native vs Cross' },
          { key: 'B', label: '둘 다 웹에서만 실행' },
          { key: 'C', label: '차이가 전혀 없음' },
          { key: 'D', label: '크로스는 하드웨어 접근 불가' },
        ],
        answerKey: 'A',
        hint: '장단점이 존재합니다.',
        explanation: '성능·생태계·개발 속도에 차이가 납니다.',
      },
      {
        id: 'mo-mid-2',
        grade: '중',
        stem: '푸시 알림을 구현할 때 필요한 요소가 아닌 것은?',
        choices: [
          { key: 'A', label: '네트워크 권한' },
          { key: 'B', label: '알림 토큰 등록', footnote: 'Device Token' },
          { key: 'C', label: '알림 서버' },
          { key: 'D', label: '화면 캡처 금지' },
        ],
        answerKey: 'D',
        hint: '권한·토큰·서버가 핵심',
        explanation: '사용자 동의와 채널 설정도 필요합니다.',
      },
      {
        id: 'mo-mid-3',
        grade: '중',
        stem: '위치기반 서비스를 만들 때 개인정보를 보호하는 방법은?',
        choices: [
          { key: 'A', label: '최소한의 권한만 요청', footnote: 'Least privilege' },
          { key: 'B', label: '모든 권한을 한 번에' },
          { key: 'C', label: '좌표를 평문으로 로그' },
          { key: 'D', label: '기간 제한 없이 보관' },
        ],
        answerKey: 'A',
        hint: '목적 범위 내 최소 수집',
        explanation: '동의·암호화·보존기간 관리가 필요합니다.',
      },
      {
        id: 'mo-mid-4',
        grade: '중',
        stem: '이미지 목록 스크롤이 끊긴다면 우선 고려할 최적화는?',
        choices: [
          { key: 'A', label: '썸네일/캐시/지연 로딩', footnote: 'Thumb/Cache/Lazy' },
          { key: 'B', label: '원본만 사용' },
          { key: 'C', label: '매 프레임 GC 강제' },
          { key: 'D', label: '동기 네트워크 호출' },
        ],
        answerKey: 'A',
        hint: '용량·렌더 비용 감소',
        explanation: '리스트/그리드에서 필수 최적화입니다.',
      },
      {
        id: 'mo-mid-5',
        grade: '중',
        stem: '앱 상태를 유지하며 화면 전환을 구현하려면 어떤 패턴이 유용한가요?',
        choices: [
          { key: 'A', label: '네비게이션 스택', footnote: 'Stack/Router' },
          { key: 'B', label: '무작위 점프' },
          { key: 'C', label: '강제 종료 반복' },
          { key: 'D', label: '스크린샷 저장' },
        ],
        answerKey: 'A',
        hint: '뒤로가기/앞으로가기',
        explanation: '스택 기반 네비게이션이 일반적입니다.',
      },

      // ── 고등(5)
      {
        id: 'mo-hi-1',
        grade: '고',
        stem: '앱 스토어 배포에서 서명(Signing)의 목적은?',
        choices: [
          { key: 'A', label: '앱 무결성과 개발자 신원 보증', footnote: 'Code Signing' },
          { key: 'B', label: '이미지 색상 변경' },
          { key: 'C', label: '파일 이름 미리보기' },
          { key: 'D', label: '폰트 교체만' },
        ],
        answerKey: 'A',
        hint: '악성 변조 방지',
        explanation: '키스토어/프로비저닝 프로파일이 필요합니다.',
      },
      {
        id: 'mo-hi-2',
        grade: '고',
        stem: '배터리 소모를 줄이기 위한 네트워크 최적화 전략은?',
        choices: [
          { key: 'A', label: '요청 합치기/백오프/배치 전송', footnote: 'Batching/Backoff' },
          { key: 'B', label: '매초 풀폴링' },
          { key: 'C', label: '대용량 파일 실시간 스트리밍' },
          { key: 'D', label: '스크린 항상 켜두기' },
        ],
        answerKey: 'A',
        hint: '전송 횟수·시점 조절',
        explanation: '불필요 트래픽을 줄여 전력 사용을 낮춥니다.',
      },
      {
        id: 'mo-hi-3',
        grade: '고',
        stem: '크래시 로그에서 재현이 어려운 버그를 분석할 때 도움이 되는 것은?',
        choices: [
          { key: 'A', label: '스택 트레이스/세션 리플레이', footnote: 'Stacktrace/Replay' },
          { key: 'B', label: '사용자 탓' },
          { key: 'C', label: '운에 맡기기' },
          { key: 'D', label: '로그 끄기' },
        ],
        answerKey: 'A',
        hint: '맥락 파악이 핵심',
        explanation: '오류+상태 기록으로 원인을 좁힙니다.',
      },
      {
        id: 'mo-hi-4',
        grade: '고',
        stem: '크로스 플랫폼에서 브리지 호출이 잦아 병목이 생길 때의 해결책은?',
        choices: [
          { key: 'A', label: '네이티브 모듈화/배치 처리', footnote: 'Bridge Optimization' },
          { key: 'B', label: '모든 호출 동기화' },
          { key: 'C', label: 'UI 스레드 장시간 점유' },
          { key: 'D', label: '이미지 원본만 사용' },
        ],
        answerKey: 'A',
        hint: '왕복 비용 최소화',
        explanation: '빈번한 호출은 합치거나 네이티브로 이전합니다.',
      },
      {
        id: 'mo-hi-5',
        grade: '고',
        stem: '스토어 리뷰 대응의 올바른 절차는?',
        choices: [
          { key: 'A', label: '신속한 확인·재현·패치 후 릴리즈 노트 공유', footnote: 'Release/Changelog' },
          { key: 'B', label: '무시하기' },
          { key: 'C', label: '별점 요청만 반복' },
          { key: 'D', label: '임의 삭제' },
        ],
        answerKey: 'A',
        hint: '신뢰가 품질입니다.',
        explanation: '투명한 소통이 사용자 만족도에 직결됩니다.',
      },
    ],
  },
};
